pipeline:

  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker build -t reference-data-api-service:$${DRONE_COMMIT_SHA} .
    when:
      event: push

  unit_tests:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker run -t reference-data-api-service:$${DRONE_COMMIT_SHA} sh -c "npm run test"
    when:
      event: push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/reference-data-api-service
    tags:
      - ${DRONE_BUILD_NUMBER}
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      branch: master
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - DEV_HOSTNAME
      - DEV_KUBE_NAMESPACE
      - DEV_KUBE_SERVER
      - DEV_KUBE_TOKEN
      - DEV_LOG_LEVEL
      - DEV_DB_CONNECTION_STRING
      - DEV_READ_ONLY_ROLE
    commands:
      - export HOSTNAME=$${DEV_HOSTNAME}
      - export KUBE_NAMESPACE=$${DEV_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${DEV_KUBE_SERVER}
      - export KUBE_TOKEN=$${DEV_KUBE_TOKEN}
      - export LOG_LEVEL=$${DEV_LOG_LEVEL}
      - export DB_CONNECTION_STRING=$${DEV_DB_CONNECTION_STRING}
      - export READ_ONLY_ROLE=$${DEV_READ_ONLY_ROLE}
      - kd --insecure-skip-tls-verify -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      branch: master
      event: push

  deploy_to_prod:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - PROD_HOSTNAME
      - PROD_KUBE_NAMESPACE
      - PROD_KUBE_SERVER
      - PROD_KUBE_TOKEN
      - PROD_LOG_LEVEL
      - PROD_DB_CONNECTION_STRING
      - PROD_READ_ONLY_ROLE
    commands:
      - export HOSTNAME=$${PROD_HOSTNAME}
      - export KUBE_NAMESPACE=$${PROD_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${PROD_KUBE_SERVER}
      - export KUBE_TOKEN=$${PROD_KUBE_TOKEN}
      - export LOG_LEVEL=$${PROD_LOG_LEVEL}
      - export DB_CONNECTION_STRING=$${PROD_DB_CONNECTION_STRING}
      - export READ_ONLY_ROLE=$${PROD_READ_ONLY_ROLE}
      - kd --insecure-skip-tls-verify -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      event: deployment
      environment: production
