---
pipeline:

  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker build -t ref-data-api:$${DRONE_COMMIT_SHA} .
    when:
      event: push

  unit_tests:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker run -t ref-data-api:$${DRONE_COMMIT_SHA} sh -c "npm run test"
    when:
      event: push

  lint_checks:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker run -t ref-data-api:$${DRONE_COMMIT_SHA} sh -c "npm run lint -- app/"
    when:
      event: push

  synch_dev_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
    secrets:
      - source: DEV_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: DEV_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
      branch: master
      event: push

  synch_staging_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
    secrets:
      - source: STAGING_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: STAGING_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
      event: deployment
      environment: staging

  synch_production_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
    secrets:
      - source: PRODUCTION_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: PRODUCTION_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
      event: deployment
      environment: production

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
    - source: QUAY_USERNAME
      target: DOCKER_USERNAME
    - source: QUAY_PASSWORD
      target: DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/ref-data-api
    tags: ${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - source: DEV_API_REF_IMAGE
        target: API_REF_IMAGE
      - source: DEV_API_REF_KEYCLOAK_CLIENT_ID
        target: API_REF_KEYCLOAK_CLIENT_ID
      - source: DEV_API_REF_KUBE_NAMESPACE
        target: KUBE_NAMESPACE
      - source: DEV_API_REF_KUBE_TOKEN
        target: KUBE_TOKEN
      - source: DEV_API_REF_LIMIT_ROWS
        target: LIMIT_ROWS
      - source: DEV_API_REF_LOG_LEVEL
        target: API_REF_LOG_LEVEL
      - source: DEV_API_REF_NAME
        target: API_REF_NAME
      - source: DEV_API_REF_PORT
        target: API_REF_PORT
      - source: DEV_API_REF_URL
        target: API_REF_URL
      - source: DEV_DB_REF_HOSTNAME
        target: DB_REF_HOSTNAME
      - source: DEV_DB_REF_OPTIONS
        target: DB_REF_OPTIONS
      - source: DEV_DB_REF_PORT
        target: DB_REF_PORT
      - source: DEV_DB_REF_PROTOCOL
        target: DB_REF_PROTOCOL
      - source: DEV_DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD
        target: DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD
      - source: DEV_DB_REF_REFERENCE_AUTHENTICATOR_USERNAME
        target: DB_REF_REFERENCE_AUTHENTICATOR_USERNAME
      - source: DEV_DB_REF_REFERENCE_DBNAME
        target: DB_REF_REFERENCE_DBNAME
      - source: DEV_DB_REF_REFERENCE_SCHEMA
        target: DB_REF_REFERENCE_SCHEMA
      - source: DEV_KEYCLOAK_PROTOCOL
        target: KEYCLOAK_PROTOCOL
      - source: DEV_KEYCLOAK_REALM
        target: KEYCLOAK_REALM
      - source: DEV_KEYCLOAK_URL
        target: KEYCLOAK_URL
      - source: DEV_KUBE_SERVER
        target: KUBE_SERVER
      - source: NGINX_IMAGE
        target: NGINX_IMAGE
      - source: NGINX_TAG
        target: NGINX_TAG
    commands:
      - export API_REF_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml -f kube/secret.yml -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      branch: master
      event: push

  deploy_to_staging:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - source: STAGING_API_REF_IMAGE
        target: API_REF_IMAGE
      - source: STAGING_API_REF_KEYCLOAK_CLIENT_ID
        target: API_REF_KEYCLOAK_CLIENT_ID
      - source: STAGING_API_REF_KUBE_NAMESPACE
        target: KUBE_NAMESPACE
      - source: STAGING_API_REF_KUBE_TOKEN
        target: KUBE_TOKEN
      - source: STAGING_API_REF_LIMIT_ROWS
        target: LIMIT_ROWS
      - source: STAGING_API_REF_LOG_LEVEL
        target: API_REF_LOG_LEVEL
      - source: STAGING_API_REF_NAME
        target: API_REF_NAME
      - source: STAGING_API_REF_PORT
        target: API_REF_PORT
      - source: STAGING_API_REF_URL
        target: API_REF_URL
      - source: STAGING_DB_REF_HOSTNAME
        target: DB_REF_HOSTNAME
      - source: STAGING_DB_REF_OPTIONS
        target: DB_REF_OPTIONS
      - source: STAGING_DB_REF_PORT
        target: DB_REF_PORT
      - source: STAGING_DB_REF_PROTOCOL
        target: DB_REF_PROTOCOL
      - source: STAGING_DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD
        target: DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD
      - source: STAGING_DB_REF_REFERENCE_AUTHENTICATOR_USERNAME
        target: DB_REF_REFERENCE_AUTHENTICATOR_USERNAME
      - source: STAGING_DB_REF_REFERENCE_DBNAME
        target: DB_REF_REFERENCE_DBNAME
      - source: STAGING_DB_REF_REFERENCE_SCHEMA
        target: DB_REF_REFERENCE_SCHEMA
      - source: STAGING_KEYCLOAK_PROTOCOL
        target: KEYCLOAK_PROTOCOL
      - source: STAGING_KEYCLOAK_REALM
        target: KEYCLOAK_REALM
      - source: STAGING_KEYCLOAK_URL
        target: KEYCLOAK_URL
      - source: STAGING_KUBE_SERVER
        target: KUBE_SERVER
      - source: NGINX_IMAGE
        target: NGINX_IMAGE
      - source: NGINX_TAG
        target: NGINX_TAG
    commands:
      - export API_REF_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml -f kube/secret.yml -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      event: deployment
      environment: staging

  deploy_to_prod:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - source: PRODUCTION_API_REF_IMAGE
        target: API_REF_IMAGE
      - source: PRODUCTION_API_REF_KEYCLOAK_CLIENT_ID
        target: API_REF_KEYCLOAK_CLIENT_ID
      - source: PRODUCTION_API_REF_KUBE_NAMESPACE
        target: KUBE_NAMESPACE
      - source: PRODUCTION_API_REF_KUBE_TOKEN
        target: KUBE_TOKEN
      - source: PRODUCTION_API_REF_LIMIT_ROWS
        target: LIMIT_ROWS
      - source: PRODUCTION_API_REF_LOG_LEVEL
        target: API_REF_LOG_LEVEL
      - source: PRODUCTION_API_REF_NAME
        target: API_REF_NAME
      - source: PRODUCTION_API_REF_PORT
        target: API_REF_PORT
      - source: PRODUCTION_API_REF_URL
        target: API_REF_URL
      - source: PRODUCTION_DB_REF_HOSTNAME
        target: DB_REF_HOSTNAME
      - source: PRODUCTION_DB_REF_OPTIONS
        target: DB_REF_OPTIONS
      - source: PRODUCTION_DB_REF_PORT
        target: DB_REF_PORT
      - source: PRODUCTION_DB_REF_PROTOCOL
        target: DB_REF_PROTOCOL
      - source: PRODUCTION_DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD
        target: DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD
      - source: PRODUCTION_DB_REF_REFERENCE_AUTHENTICATOR_USERNAME
        target: DB_REF_REFERENCE_AUTHENTICATOR_USERNAME
      - source: PRODUCTION_DB_REF_REFERENCE_DBNAME
        target: DB_REF_REFERENCE_DBNAME
      - source: PRODUCTION_DB_REF_REFERENCE_SCHEMA
        target: DB_REF_REFERENCE_SCHEMA
      - source: PRODUCTION_KEYCLOAK_PROTOCOL
        target: KEYCLOAK_PROTOCOL
      - source: PRODUCTION_KEYCLOAK_REALM
        target: KEYCLOAK_REALM
      - source: PRODUCTION_KEYCLOAK_URL
        target: KEYCLOAK_URL
      - source: PRODUCTION_KUBE_SERVER
        target: KUBE_SERVER
      - source: NGINX_IMAGE
        target: NGINX_IMAGE
      - source: NGINX_TAG
        target: NGINX_TAG
    commands:
      - export API_REF_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml -f kube/secret.yml -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      event: deployment
      environment: production

  notify:
    image: plugins/slack
    secrets: [ SLACK_WEBHOOK ]
    channel: cop-deployments
    username: Drone Build Watcher
    template: >
      {{#build.deployTo}}
        *{{repo.name}} - Build {{build.number}} - {{uppercasefirst build.deployTo}} - {{uppercase build.status}}*
        {{build.link}}
      {{else}}
        *{{repo.name}} - Build {{build.number}} - Development - {{uppercase build.status}}*
        {{build.link}}
      {{/build.deployTo}}
    when:
      branch: master
      event: [ push, deployment ]
      status: [ success, failure ]
