---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{.API_REF_NAME}}-ingress
  labels:
    cert-manager.io/solver: http01
  annotations:
    cert-manager.io/enabled: "true"
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - host: {{.API_REF_URL}}
    http:
      paths:
      - backend:
          serviceName: {{.API_REF_NAME}}-service
          servicePort: 10443
        path: /
  tls:
  - hosts:
    - {{.API_REF_URL}}
    secretName: {{.API_REF_NAME}}-cmio
