---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{.API_REF_NAME}}-service
  name: {{.API_REF_NAME}}-service
spec:
  ports:
  - name: https
    port: 443
    targetPort: 10443
  selector:
    name: {{.API_REF_NAME}}
